### ISSUE TITLE
Kimetsu no Yaiba Ep 24 Sub Errata

### ISSUE THREAD

**Issue by Nostaljaded** [Kaleido-subs/Kaleidosubs#4]
Kimetsu no Yaiba Ep 24 subtitle errata based on latest commit d383c20, introduced in commit 4b0cfb6.
Compared against external subtitle file from older commit 2487c34.

> **02:31 - No text styling for episode title & presence of underscore symbol** but both issues absent for Ep 25 in commit 4b0cfb6. Absence of episode title's new font in 'Ep 24 mkv file'?

> **16:32 - No auto line break**. Aegisub settings changed (in other words, auto line break disabled) in subtitle file?

P.S. Only viewed Ep 24-26 in mpv player, so good to probe the cause of Ep 24 regression in case latest version for earlier episodes are affected as well.

### 02:31
![1](https://user-images.githubusercontent.com/28423237/87214630-6a593600-c2fc-11ea-93fa-3f69a0f1d87d.jpg)
![2](https://user-images.githubusercontent.com/28423237/87214632-6cbb9000-c2fc-11ea-8d5f-1845db6b0fa0.jpg)
![5](https://user-images.githubusercontent.com/28423237/87214635-6decbd00-c2fc-11ea-9666-b5b7b5a954a5.jpg)
![6](https://user-images.githubusercontent.com/28423237/87214636-6e855380-c2fc-11ea-8915-ce2eef8ae77c.jpg)

### 16:32
![3](https://user-images.githubusercontent.com/28423237/87214633-6d542680-c2fc-11ea-9fb9-fd49fc4fd5b6.jpg)
![4](https://user-images.githubusercontent.com/28423237/87214634-6decbd00-c2fc-11ea-9313-9478163e67e9.jpg)

**Comment by LightArrowsEXE** [comment]
> 02:31 - No text styling for episode title & presence of underscore symbol but both issues absent for Ep 25 in commit 4b0cfb6. Absence of episode title's new font in 'Ep 24 mkv file'?
Font is missing from the released episode because I changed the styling after. All the fonts will be included in the final batch release, and can also be found in Ep25 and Ep26 already.
Underscore is there to replace the space, since it increases the difference between spaces way more and doesn't render anything.

With underscores:
![](https://i.imgur.com/gpY2vEg.png)

With regular spaces:
![](https://i.imgur.com/Fmg2JyA.png)

> 16:32 - No auto line break. Aegisub settings changed (in other words, auto line break disabled) in subtitle file?
Wrap style is set to 2 (No word wrapping) as a method to force players to always render the subs the same way. Without them, some players and settings may force linebreaks in different areas causing three-liners. I've forcibly set all of them for the batch in advance, thinking I had already set all the linebreaks and if not, fixing them as I go through the episodes. I'll fix up that particular line in advance.
