### ISSUE TITLE
Kimetsu no Yaiba Ep. 20 - Grammar error

### ISSUE THREAD

**Issue by SuperfieldCU** [Kaleido-subs/Kaleidosubs#5]
Line 90: Do you want me save you?

->

Do you want me to save you?

**Comment by The0x539** [comment]
Fixed in the internal project repo since 2021-02-25.

**Comment by LightArrowsEXE** [comment]
Will merge for now. The Yaiba directory will be removed from here once the project repository is public (which will be once we release the final batch)

**Comment by SuperfieldCU** [comment]
I tried to make a PR for it, but it wouldn't let me.

I obviously don't know the status of your internal files, but there's another error: episode 14's Sign style has its anchoring set to 2 instead of 5 like all the others. That in and of itself isn't a problem, I'm sure it was for some of the complex signs in that episode, but it also incorrectly offset the Demon Slayer logo in the OP. An {\an5} tag should be added to that line.

**Comment by The0x539** [comment]
At some point, I went through and made sure that all instances of each style are the same throughout the project:
![image](https://user-images.githubusercontent.com/7350294/114279996-eb18a000-99fc-11eb-9536-020a56da27c2.png)

In addition, we set things up so that each episode has separate dialogue and TS files that get merged while muxing, as well as one shared subtitle file for the OP and one for the ED that get timeshifted for each episode, so everything about those (including the sign, because Light decided to put that in the shared OP file) should be identical across episodes.

I've probably inadvertently messed up some other stuff in the process, but I've done a lot of work with leveraging technology to try and produce consistency or, barring that, at least *checking for* consistency (e.g., that image above, where it's clear that there are no longer slightly-different versions of style definitions, or making sure that all the `PREVIEW` signs are consistent and not messed up).
